### ISSUE TITLE
Arduino Makefile

### ISSUE THREAD

**Issue by nixpulvis** [nixpulvis/quadcopter#10]
Using the Arduino IDE is an awful way to live. We need a makefile to compile and upload out C to the Arduino directly.

[Great information](http://bleaklow.com/2010/06/04/a_makefile_for_arduino_sketches.html)

**Comment by alexjohnson505** [comment]
Woah!

**Comment by nixpulvis** [comment]
Just closing old issues. Though I have been thinking about working on this again... Would love to have people to work on it with :/

**Comment by dcalacci** [comment]
yes yes yes!

**Comment by nixpulvis** [comment]
@dcalacci is that interest in helping I hear?
